version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kaua
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - redebd
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongobdata:/data/db

  mongoexpres:
    image: mongo-express
    container_name: mongoexpres
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kaua
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
    networks:
      - redebd
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb

networks:
  redebd:
    driver: bridge

volumes:
  mongobdata:
    driver: local
    